name 'serverascode-swuppet'
version '0.0.5'
dependency 'puppetlabs/ntp', 'puppetlabs/apt', 'puppetlabs/mysql'
summary "Deploy OpenStack Swift"
description 'Deploys OpenStack Swift'
project_page 'http://github.com/curtisgithub/swuppet'
author 'curtis@serverascode.com'